name = "nxoland-frontend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist"

[env.production]
NPM_CONFIG_PRODUCTION = "false"
NPM_CONFIG_USER_AGENT = "npm"

