import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ar';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  ar: {
   // Navbar
'nav.home': 'الرئيسية',
'nav.marketplace': 'المتجر',
'nav.sell': 'بيع حساب',
'nav.orders': 'طلباتي',
'nav.wallet': 'المحفظة',
'nav.profile': 'الملف الشخصي',
'nav.admin': 'لوحة التحكم',
'nav.members': 'الأعضاء',
'nav.leaderboard': 'المتصدرين',
'nav.help': 'المساعدة',
'nav.disputes': 'النزاعات',
'nav.myListings': 'إعلاناتي',
'nav.kyc': 'توثيق الهوية',
    'nav.notifications': 'الإشعارات',
    'nav.settings': 'الإعدادات',
    'nav.logout': 'تسجيل الخروج',
    'nav.login': 'تسجيل الدخول',
    'nav.suggestions': 'الاقتراحات والتقييم',
'nav.community': 'المجتمع',

// Home
'home.hero.title': 'NXOLand — منصتك الآمنة لتداول حسابات الألعاب',
'home.hero.subtitle': 'بيع وشراء حساباتك المفضلة بسهولة، سرعة، وحماية تامة عبر نظام وساطة ذكي',
'home.hero.browseAccounts': 'تصفح الحسابات',
'home.hero.learnMore': 'اعرف المزيد',

'home.features.security': '🔒 أمان مضمون',
'home.features.fast': '⚡ معاملات سريعة',
'home.features.support': '💬 دعم مباشر 24/7',

'home.whyChoose': 'ليش تختار NXOLand؟',

'home.feature1.title': 'نظام وساطة آمن',
'home.feature1.desc': 'نحفظ حق البائع والمشتري من أول عملية حتى آخر خطوة',

'home.feature2.title': 'دعم متواصل',
'home.feature2.desc': 'فريق دعم متواجد دائمًا عبر ديسكورد لخدمتك في أي وقت',

'home.feature3.title': 'أسعار عادلة وتنافسية',
'home.feature3.desc': 'نقدم تجربة بيع وشراء بأسعار مميزة وبدون عمولات مبالغ فيها',

'home.feature4.title': 'تحويل فوري وآمن',
'home.feature4.desc': 'يتم التحويل للبائع فور تأكيد المشتري استلام الحساب',

'home.howItWorks': 'طريقة العمل',

'home.step1.title': 'اختر الحساب المناسب',
'home.step1.desc': 'تصفح حسابات متعددة حسب اللعبة، السعر، والمستوى',

'home.step2.title': 'ادفع بأمان تام',
'home.step2.desc': 'استخدم نظام Tap للدفع الموثوق والمشفر بالكامل',

'home.step3.title': 'استلم حسابك فورًا',
'home.step3.desc': 'بعد الدفع يتم تسليم الحساب تلقائيًا مع ضمان الحقوق للطرفين',

'home.cta.title': 'ابدأ الآن بثقة',
'home.cta.subtitle': 'انضم لآلاف اللاعبين اللي يثقون في NXOLand لتداول حساباتهم بأمان',
'home.cta.getStarted': 'ابدأ التداول',

'home.footer.rights': '© جميع الحقوق محفوظة لـ NXOLand',
'home.footer.terms': 'الشروط والأحكام',
'home.footer.privacy': 'سياسة الخصوصية',
'home.footer.support': 'الدعم الفني',

    
    // Sell
    'sell.title': 'اختر اللعبة',
    'sell.subtitle': 'حدد اللعبة التي تريد بيع حساباتها',
    'sell.comingSoon': 'المزيد من الألعاب قريباً...',
    'sell.selectCategory': 'اختر الفئة',
    'sell.categorySubtitle': 'اختر نوع الحساب الذي تريد بيعه',
    'sell.explore': 'استكشف',
    'sell.price': 'السعر',
    'sell.description': 'الوصف',
    'sell.gaming.title': 'حسابات الألعاب',
    'sell.gaming.description': 'بيع حسابات ألعابك',
    'sell.social.title': 'حسابات التواصل الاجتماعي',
    'sell.social.description': 'بيع حسابات وسائل التواصل',
    'sell.social.followers': 'المتابعين',
    'sell.social.likes': 'الإعجابات',
    'sell.social.views': 'المشاهدات',
    'sell.social.posts': 'المنشورات',
    'sell.social.engagement': 'معدل التفاعل',
    'sell.social.verification': 'حالة التوثيق',
    'sell.social.verified': 'موثق',
    'sell.social.unverified': 'غير موثق',
    'sell.social.tiktok.title': 'بيع حساب تيك توك',
    'sell.social.tiktok.subtitle': 'أدخل تفاصيل حساب تيك توك الخاص بك',
    'sell.social.tiktok.description': 'بيع حسابات تيك توك',
    'sell.social.tiktok.username': 'اسم المستخدم',
    'sell.social.tiktok.descriptionPlaceholder': 'صف حسابك، النيش، نوع المحتوى، إلخ...',
    'sell.social.instagram.title': 'بيع حساب إنستغرام',
    'sell.social.instagram.subtitle': 'أدخل تفاصيل حساب إنستغرام الخاص بك',
    'sell.social.instagram.description': 'بيع حسابات إنستغرام',
    'sell.social.instagram.username': 'اسم المستخدم',
    'sell.social.instagram.descriptionPlaceholder': 'صف حسابك، النيش، نوع المحتوى، إلخ...',
    'sell.social.accountDescription': 'وصف الحساب',
    'sell.social.descriptionPlaceholder': 'صف حسابك، النيش، نوع المحتوى، إلخ...',
    'sell.social.accountWithPrimaryEmail': 'الحساب مع البريد الإلكتروني الأساسي',
    'sell.social.accountLinkedToPhone': 'الحساب مرتبط برقم هاتف',
    'sell.social.confirmOwnership.title': 'تأكيد الملكية ومعلومات التسليم',
    'sell.social.confirmOwnership.description': 'لضمان بيئة آمنة لبيع وشراء الحسابات، يجب عليك إكمال الخطوات أدناه لإضافة حسابك.',
    'sell.social.confirmOwnership.instruction': 'اضغط على زر "ضع الكلمة أدناه في السيرة الذاتية لحسابك" للمتابعة',
    'sell.social.confirmOwnership.theWord': 'الكلمة',
    'sell.social.confirmOwnership.copy': 'نسخ',
    'sell.social.confirmOwnership.confirm': 'تأكيد الملكية',
    'sell.social.pledge1': 'أتعهد بأن يكون وصف المنتج خاليًا من أي وسائل اتصال خارج المنصة، بأي طريقة كانت، سواء كانت مباشرة أو غير مباشرة.',
    'sell.social.pledge2': 'أتعهد بتحمل المسؤولية القانونية الكاملة عن جميع الإجراءات المتخذة أو الصادرة عن الحساب المعني من تاريخ إنشائه أو شرائه حتى تاريخ بيعه على منصة المستخدم، وأضمن أنه خالٍ من أي جرائم إلكترونية.',
    'sell.social.deliveryInfo.title': 'معلومات التسليم',
    'sell.social.deliveryInfo.description': 'أدخل بيانات الحساب التي سيتم تسليمها للمشتري',
    'sell.social.deliveryInfo.email': 'البريد الإلكتروني',
    'sell.social.deliveryInfo.password': 'كلمة المرور',
    'sell.social.deliveryInfo.instructions': 'تعليمات التسليم',
    'sell.social.deliveryInfo.instructionsPlaceholder': 'أي معلومات إضافية للمشتري حول التسليم...',
    
    // Listing
    'listing.success': 'تم إنشاء الإعلان بنجاح!',
    'listing.successDescription': 'سيتم مراجعة إعلانك ونشره قريباً.',
    'listing.creating': 'جاري الإنشاء...',
    'listing.create': 'إنشاء إعلان',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.back': 'رجوع',
    'common.confirm': 'تأكيد',
    'common.close': 'إغلاق',
    'common.submit': 'إرسال',
    'common.update': 'تحديث',
    'common.download': 'تحميل',
    'common.upload': 'رفع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.page': 'صفحة',
    'common.of': 'من',
    'common.showing': 'عرض',
    'common.results': 'نتائج',
    'common.noResults': 'لا توجد نتائج',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    'common.warning': 'تحذير',
    'common.info': 'معلومات',
    
    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.fullName': 'الاسم الكامل',
    'auth.phone': 'رقم الهاتف',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.rememberMe': 'تذكرني',
    'auth.haveAccount': 'لديك حساب؟',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.loginButton': 'تسجيل الدخول',
    'auth.signupButton': 'إنشاء حساب',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح',
    'auth.signupSuccess': 'تم إنشاء الحساب بنجاح',
    'auth.loginError': 'فشل تسجيل الدخول',
    'auth.signupError': 'فشل إنشاء الحساب',
    'auth.invalidEmail': 'يرجى إدخال بريد إلكتروني صحيح',
    'auth.passwordTooShort': 'كلمة المرور يجب أن تكون على الأقل',
    'auth.passwordMismatch': 'كلمات المرور غير متطابقة',
    'auth.nameTooShort': 'الاسم يجب أن يكون على الأقل',
    'auth.agreeToTerms': 'بإنشاء حساب، أنت توافق على',
    'auth.and': 'و',
    'auth.backToHome': 'العودة للصفحة الرئيسية',
    'auth.processing': 'جاري المعالجة...',
    'auth.securityVerification': 'يرجى إكمال التحقق الأمني',
    
    // Marketplace
    'marketplace.title': 'السوق',
    'marketplace.subtitle': 'تصفح جميع الحسابات المتاحة',
    'marketplace.searchPlaceholder': 'ابحث عن حسابات...',
    'marketplace.filterBy': 'تصفية حسب',
    'marketplace.sortBy': 'ترتيب حسب',
    'marketplace.allGames': 'جميع الألعاب',
    'marketplace.priceRange': 'نطاق السعر',
    'marketplace.level': 'المستوى',
    'marketplace.server': 'السيرفر',
    'marketplace.latest': 'الأحدث',
    'marketplace.priceHigh': 'السعر (الأعلى أولاً)',
    'marketplace.priceLow': 'السعر (الأقل أولاً)',
    'marketplace.levelHigh': 'المستوى (الأعلى أولاً)',
    'marketplace.noListings': 'لا توجد إعلانات',
    'marketplace.noListingsDesc': 'لم يتم العثور على حسابات تطابق البحث',
    'marketplace.tryDifferent': 'حاول تعديل البحث أو الفلتر',
    'marketplace.verified': 'موثق',
    'marketplace.featured': 'مميز',
    'marketplace.viewDetails': 'عرض التفاصيل',
    
    // Product Details
    'product.details': 'تفاصيل الحساب',
    'product.price': 'السعر',
    'product.level': 'المستوى',
    'product.server': 'السيرفر',
    'product.seller': 'البائع',
    'product.description': 'الوصف',
    'product.specifications': 'المواصفات',
    'product.images': 'الصور',
    'product.buyNow': 'شراء الآن',
    'product.addToCart': 'أضف للسلة',
    'product.sellerInfo': 'معلومات البائع',
    'product.sellerRating': 'تقييم البائع',
    'product.totalSales': 'إجمالي المبيعات',
    'product.memberSince': 'عضو منذ',
    'product.responseTime': 'وقت الاستجابة',
    'product.deliveryTime': 'وقت التسليم',
    'product.viewProfile': 'عرض الملف الشخصي',
    'product.reportListing': 'الإبلاغ عن الإعلان',
    'product.share': 'مشاركة',
    'product.clickToEnlarge': 'اضغط للتكبير',
    
    // Checkout
    'checkout.title': 'إتمام الشراء',
    'checkout.orderSummary': 'ملخص الطلب',
    'checkout.productDetails': 'تفاصيل المنتج',
    'checkout.subtotal': 'المجموع الفرعي',
    'checkout.serviceFee': 'رسوم الخدمة',
    'checkout.total': 'الإجمالي',
    'checkout.paymentMethod': 'طريقة الدفع',
    'checkout.agreeToTerms': 'أوافق على الشروط والأحكام',
    'checkout.confirmPurchase': 'تأكيد الشراء',
    'checkout.processing': 'جاري المعالجة...',
    'checkout.securePayment': 'دفع آمن عبر',
    'checkout.buyerProtection': 'حماية المشتري لمدة 12 ساعة',
    'checkout.deliveryInfo': 'معلومات التسليم',
    'checkout.instantDelivery': 'تسليم فوري بعد الدفع',
    'checkout.mustAgreeTerms': 'يجب الموافقة على الشروط والأحكام',
    
    // Orders
    'orders.title': 'طلباتي',
    'orders.subtitle': 'عرض وإدارة جميع طلباتك',
    'orders.searchPlaceholder': 'ابحث برقم الطلب، المنتج، أو البائع...',
    'orders.filterByRole': 'عرض الطلبات:',
    'orders.all': 'الكل',
    'orders.asBuyer': 'كمشتري',
    'orders.asSeller': 'كبائع',
    'orders.status': 'الحالة',
    'orders.pending': 'بانتظار الدفع',
    'orders.paid': 'تم الدفع',
    'orders.escrowHold': 'قيد الضمان',
    'orders.completed': 'مكتمل',
    'orders.cancelled': 'ملغي',
    'orders.disputed': 'قيد النزاع',
    'orders.noOrders': 'لا توجد طلبات',
    'orders.noOrdersDesc': 'لم تقم بأي عمليات شراء بعد',
    'orders.noOrdersFilter': 'لا توجد طلبات تطابق الفلتر المحدد',
    'orders.browseMarket': 'تصفح السوق',
    'orders.viewDetails': 'عرض التفاصيل',
    'orders.contactSeller': 'التواصل مع البائع',
    'orders.openDispute': 'فتح نزاع',
    'orders.viewDispute': 'عرض النزاع',
    'orders.confirmReceipt': 'تأكيد الاستلام',
    'orders.orderNumber': 'رقم الطلب',
    'orders.date': 'التاريخ',
    'orders.buyer': 'المشتري',
    'orders.seller': 'البائع',
    'orders.amount': 'المبلغ',
    'orders.stats.total': 'إجمالي',
    'orders.stats.asBuyer': 'كمشتري',
    'orders.stats.asSeller': 'كبائع',
    'orders.stats.inEscrow': 'قيد الضمان',
    'orders.stats.completed': 'مكتمل',
    'orders.stats.cancelled': 'ملغي',
    
    // Order Details
    'order.title': 'تفاصيل الطلب',
    'order.status': 'حالة الطلب',
    'order.timeline': 'المراحل',
    'order.productInfo': 'معلومات المنتج',
    'order.accountDetails': 'تفاصيل الحساب',
    'order.paymentInfo': 'معلومات الدفع',
    'order.actions': 'الإجراءات',
    'order.confirmDelivery': 'تأكيد الاستلام',
    'order.openDispute': 'فتح نزاع',
    'order.cancelOrder': 'إلغاء الطلب',
    'order.contactSupport': 'التواصل مع الدعم',
    'order.downloadInvoice': 'تحميل الفاتورة',
    'order.escrowPeriod': 'فترة الضمان',
    'order.escrowEndsIn': 'ينتهي الضمان خلال',
    'order.hours': 'ساعة',
    'order.minutes': 'دقيقة',
    'order.delivered': 'تم التسليم',
    'order.deliveredAt': 'تم التسليم في',
    
    // Wallet
    'wallet.title': 'المحفظة',
    'wallet.balance': 'الرصيد المتاح',
    'wallet.pending': 'قيد الانتظار',
    'wallet.total': 'الإجمالي',
    'wallet.withdraw': 'سحب الرصيد',
    'wallet.deposit': 'إيداع',
    'wallet.transactions': 'المعاملات',
    'wallet.withdrawalHistory': 'سجل السحوبات',
    'wallet.amount': 'المبلغ',
    'wallet.enterAmount': 'أدخل المبلغ',
    'wallet.minimumWithdrawal': 'الحد الأدنى للسحب',
    'wallet.bankAccount': 'الحساب البنكي',
    'wallet.accountNumber': 'رقم الحساب',
    'wallet.accountName': 'اسم صاحب الحساب',
    'wallet.bankName': 'اسم البنك',
    'wallet.iban': 'الآيبان (IBAN)',
    'wallet.requestWithdrawal': 'طلب السحب',
    'wallet.withdrawalRequested': 'تم طلب السحب بنجاح',
    'wallet.withdrawalPending': 'قيد المعالجة',
    'wallet.withdrawalCompleted': 'تم التحويل',
    'wallet.withdrawalFailed': 'فشل السحب',
    'wallet.transactionType': 'نوع المعاملة',
    'wallet.sale': 'بيع',
    'wallet.purchase': 'شراء',
    'wallet.withdrawal': 'سحب',
    'wallet.refund': 'استرداد',
    'wallet.fee': 'رسوم',
    'wallet.noTransactions': 'لا توجد معاملات',
    'wallet.processingTime': 'مدة المعالجة: 1-4 أيام عمل',
    
    // Profile
    'profile.title': 'الملف الشخصي',
    'profile.publicProfile': 'الملف العام',
    'profile.memberSince': 'عضو منذ',
    'profile.lastActive': 'آخر نشاط',
    'profile.verified': 'موثق',
    'profile.notVerified': 'غير موثق',
    'profile.rating': 'التقييم',
    'profile.totalSales': 'إجمالي المبيعات',
    'profile.completedOrders': 'الطلبات المكتملة',
    'profile.activeListings': 'الإعلانات النشطة',
    'profile.responseRate': 'معدل الاستجابة',
    'profile.deliveryTime': 'وقت التسليم',
    'profile.editProfile': 'تعديل الملف الشخصي',
    'profile.viewReviews': 'عرض التقييمات',
    'profile.accountSettings': 'إعدادات الحساب',
    'profile.security': 'الأمان',
    'profile.verifyAccount': 'توثيق الحساب',
    'profile.about': 'نبذة',
    'profile.noReviews': 'لا توجد تقييمات بعد',
    'profile.reviewsCount': 'تقييم',
    
    // Edit Profile
    'editProfile.title': 'تعديل الملف الشخصي',
    'editProfile.personalInfo': 'المعلومات الشخصية',
    'editProfile.name': 'الاسم',
    'editProfile.email': 'البريد الإلكتروني',
    'editProfile.phone': 'رقم الهاتف',
    'editProfile.bio': 'نبذة عني',
    'editProfile.avatar': 'الصورة الشخصية',
    'editProfile.changeAvatar': 'تغيير الصورة',
    'editProfile.saveChanges': 'حفظ التغييرات',
    'editProfile.saving': 'جاري الحفظ...',
    'editProfile.updateSuccess': 'تم تحديث الملف بنجاح',
    'editProfile.updateError': 'فشل التحديث',
    
    // Security
    'security.title': 'الأمان',
    'security.changePassword': 'تغيير كلمة المرور',
    'security.currentPassword': 'كلمة المرور الحالية',
    'security.newPassword': 'كلمة المرور الجديدة',
    'security.confirmNewPassword': 'تأكيد كلمة المرور الجديدة',
    'security.updatePassword': 'تحديث كلمة المرور',
    'security.passwordUpdated': 'تم تحديث كلمة المرور',
    'security.twoFactor': 'المصادقة الثنائية',
    'security.enable2FA': 'تفعيل المصادقة الثنائية',
    'security.disable2FA': 'تعطيل المصادقة الثنائية',
    'security.loginHistory': 'سجل تسجيل الدخول',
    'security.activeSessions': 'الجلسات النشطة',
    'security.logoutAll': 'تسجيل الخروج من جميع الأجهزة',
    
    // KYC
    'kyc.title': 'التحقق من الهوية',
    'kyc.subtitle': 'أكمل التحقق من هويتك لزيادة حد السحب',
    'kyc.status': 'حالة التحقق',
    'kyc.notStarted': 'لم يبدأ',
    'kyc.pending': 'قيد المراجعة',
    'kyc.verified': 'موثق',
    'kyc.rejected': 'مرفوض',
    'kyc.startVerification': 'بدء التحقق',
    'kyc.resubmit': 'إعادة التقديم',
    'kyc.benefits': 'فوائد التوثيق',
    'kyc.benefit1': 'زيادة حد السحب إلى $10,000',
    'kyc.benefit2': 'شارة التوثيق على ملفك الشخصي',
    'kyc.benefit3': 'زيادة الثقة من المشترين',
    'kyc.benefit4': 'أولوية في الدعم الفني',
    'kyc.requiredDocs': 'المستندات المطلوبة',
    'kyc.nationalId': 'بطاقة الهوية',
    'kyc.proofOfAddress': 'إثبات العنوان',
    'kyc.selfie': 'صورة شخصية',
    
    // My Listings
    'listings.title': 'إعلاناتي',
    'listings.subtitle': 'إدارة جميع إعلاناتك',
    'listings.createNew': 'إنشاء إعلان جديد',
    'listings.active': 'نشط',
    'listings.pending': 'قيد المراجعة',
    'listings.sold': 'مباع',
    'listings.rejected': 'مرفوض',
    'listings.draft': 'مسودة',
    'listings.noListings': 'لا توجد إعلانات',
    'listings.createFirst': 'أنشئ أول إعلان لك',
    'listings.edit': 'تعديل',
    'listings.delete': 'حذف',
    'listings.view': 'عرض',
    'listings.promote': 'ترويج',
    'listings.views': 'مشاهدة',
    'listings.inquiries': 'استفسار',
    'listings.deleteConfirm': 'هل أنت متأكد من حذف هذا الإعلان؟',
    
    // Disputes
    'disputes.title': 'النزاعات',
    'disputes.subtitle': 'إدارة النزاعات والشكاوى',
    'disputes.openDispute': 'فتح نزاع',
    'disputes.myDisputes': 'نزاعاتي',
    'disputes.status': 'الحالة',
    'disputes.open': 'مفتوح',
    'disputes.inReview': 'قيد المراجعة',
    'disputes.resolved': 'محلول',
    'disputes.closed': 'مغلق',
    'disputes.orderNumber': 'رقم الطلب',
    'disputes.reason': 'السبب',
    'disputes.description': 'الوصف',
    'disputes.evidence': 'الأدلة',
    'disputes.uploadEvidence': 'رفع دليل',
    'disputes.submitDispute': 'تقديم النزاع',
    'disputes.noDisputes': 'لا توجد نزاعات',
    'disputes.viewDetails': 'عرض التفاصيل',
    'disputes.adminResponse': 'رد الإدارة',
    'disputes.resolution': 'القرار',
    
    // Notifications
    'notifications.title': 'الإشعارات',
    'notifications.markAllRead': 'تعليم الكل كمقروء',
    'notifications.deleteAll': 'حذف الكل',
    'notifications.noNotifications': 'لا توجد إشعارات',
    'notifications.newOrder': 'طلب جديد',
    'notifications.orderUpdate': 'تحديث الطلب',
    'notifications.disputeOpened': 'نزاع جديد',
    'notifications.disputeResolved': 'تم حل النزاع',
    'notifications.paymentReceived': 'تم استلام الدفع',
    'notifications.withdrawalCompleted': 'تم السحب',
    'notifications.newReview': 'تقييم جديد',
    'notifications.kycUpdate': 'تحديث التحقق',
    
    // Members & Leaderboard
    'members.title': 'الأعضاء',
    'members.subtitle': 'تصفح أعضاء المنصة',
    'members.searchMembers': 'ابحث عن عضو...',
    'members.topSellers': 'أفضل البائعين',
    'members.topBuyers': 'أفضل المشترين',
    'members.newMembers': 'أعضاء جدد',
    'leaderboard.title': 'لوحة المتصدرين',
    'leaderboard.subtitle': 'أفضل البائعين والمشترين',
    'leaderboard.rank': 'الترتيب',
    'leaderboard.member': 'العضو',
    'leaderboard.sales': 'المبيعات',
    'leaderboard.rating': 'التقييم',
    'leaderboard.topSeller': '#1',
    
    // Reviews
    'reviews.title': 'التقييمات',
    'reviews.writeReview': 'كتابة تقييم',
    'reviews.yourRating': 'تقييمك',
    'reviews.yourReview': 'تعليقك',
    'reviews.submitReview': 'إرسال التقييم',
    'reviews.helpful': 'مفيد',
    'reviews.notHelpful': 'غير مفيد',
    'reviews.report': 'إبلاغ',
    'reviews.noReviews': 'لا توجد تقييمات بعد',
    'reviews.verifiedPurchase': 'عملية شراء موثقة',
    
    // Suggestions
    'suggestions.title': 'مركز الاقتراحات والتقييمات',
    'suggestions.subtitle': 'شارك أفكارك وقيّم تجربتك على المنصة',
    'suggestions.platformRating': 'قيّم تجربتك على المنصة',
    'suggestions.yourRating': 'تقييمك للمنصة',
    'suggestions.yourFeedback': 'أخبرنا عن تجربتك',
    'suggestions.submitRating': 'إرسال التقييم',
    'suggestions.newSuggestion': 'اقتراح لتطوير المنصة',
    'suggestions.suggestionTitle': 'عنوان الاقتراح',
    'suggestions.suggestionDesc': 'وصف الاقتراح بالتفصيل...',
    'suggestions.submitSuggestion': 'إرسال الاقتراح',
    'suggestions.upvote': 'تصويت إيجابي',
    'suggestions.downvote': 'تصويت سلبي',
    'suggestions.votes': 'صوت',
    'suggestions.status.pending': 'قيد المراجعة',
    'suggestions.status.approved': 'معتمد',
    'suggestions.status.implemented': 'تم التنفيذ',
    
    // My Listings
    'myListings.title': 'إعلاناتي',
    'myListings.subtitle': 'إدارة إعلاناتك',
    'myListings.createNew': 'إنشاء إعلان جديد',
    'myListings.all': 'الكل',
    'myListings.active': 'نشط',
    'myListings.inactive': 'غير نشط',
    'myListings.sold': 'مباع',
    'myListings.noListings': 'لا توجد إعلانات',
    'myListings.noListingsMessage': 'لم تقم بإنشاء أي إعلانات بعد',
    'myListings.getStarted': 'ابدأ البيع',
    'myListings.edit': 'تعديل',
    'myListings.delete': 'حذف',
    'myListings.markAsSold': 'تحديد كمباع',
    'myListings.reactivate': 'إعادة تفعيل',
    'myListings.deactivate': 'إيقاف',
    'myListings.deleteConfirm': 'هل أنت متأكد؟',
    'myListings.deleteMessage': 'سيتم حذف هذا الإعلان نهائياً',
    'myListings.soldConfirm': 'تحديد كمباع؟',
    'myListings.soldMessage': 'هل تريد تحديد هذا الإعلان كمباع؟',
    'myListings.stats': 'الإحصائيات',
    'myListings.views': 'مشاهدات',
    'myListings.createdAt': 'تاريخ الإنشاء',
    
    // Admin
    'admin.dashboard': 'لوحة المعلومات',
    'admin.users': 'المستخدمين',
    'admin.listings': 'الإعلانات',
    'admin.orders': 'الطلبات',
    'admin.disputes': 'النزاعات',
    'admin.notifications': 'الإشعارات',
    'admin.settings': 'الإعدادات',
    'admin.legalContent': 'المحتوى القانوني',
    'admin.stats': 'الإحصائيات',
    'admin.activity': 'النشاط الأخير',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.activeListings': 'الإعلانات النشطة',
    'admin.pendingOrders': 'الطلبات المعلقة',
    'admin.openDisputes': 'النزاعات المفتوحة',
    'admin.revenue': 'الإيرادات',
    'admin.actions': 'الإجراءات',
    'admin.ban': 'حظر',
    'admin.unban': 'إلغاء الحظر',
    'admin.verify': 'توثيق',
    'admin.reject': 'رفض',
    'admin.approve': 'موافقة',
    'admin.viewDetails': 'عرض التفاصيل',
    'admin.sendNotification': 'إرسال إشعار',
    'admin.broadcastMessage': 'رسالة عامة',
    
    // Help & Support
    'help.title': 'المساعدة',
    'help.faq': 'الأسئلة الشائعة',
    'help.contactSupport': 'التواصل مع الدعم',
    'help.searchHelp': 'ابحث عن مساعدة...',
    'help.popularTopics': 'المواضيع الشائعة',
    'help.gettingStarted': 'البدء',
    'help.buyingGuide': 'دليل الشراء',
    'help.sellingGuide': 'دليل البيع',
    'help.accountSecurity': 'أمان الحساب',
    'help.paymentsAndFees': 'الدفع والرسوم',
    
    // About
    'about.title': 'عن المنصة',
    'about.ourMission': 'مهمتنا',
    'about.ourVision': 'رؤيتنا',
    'about.ourValues': 'قيمنا',
    'about.team': 'الفريق',
    'about.contact': 'تواصل معنا',
    
    // Error Messages
    'error.404': 'الصفحة غير موجودة',
    'error.404.desc': 'عذراً، الصفحة التي تبحث عنها غير موجودة',
    'error.500': 'خطأ في الخادم',
    'error.500.desc': 'حدث خطأ غير متوقع',
    'error.networkError': 'خطأ في الاتصال',
    'error.tryAgain': 'حاول مرة أخرى',
    'error.goHome': 'العودة للرئيسية',
    'error.forbidden': 'غير مصرح',
    'error.unauthorized': 'يجب تسجيل الدخول',
    'error.sessionExpired': 'انتهت الجلسة',
    
    // Status Messages
    'status.loading': 'جاري التحميل...',
    'status.saving': 'جاري الحفظ...',
    'status.uploading': 'جاري الرفع...',
    'status.processing': 'جاري المعالجة...',
    'status.success': 'تم بنجاح',
    'status.failed': 'فشل',
    'status.pending': 'قيد الانتظار',
    'status.completed': 'مكتمل',
    'status.cancelled': 'ملغي',
    
    // Time & Date
    'time.justNow': 'الآن',
    'time.minutesAgo': 'منذ {n} دقيقة',
    'time.hoursAgo': 'منذ {n} ساعة',
    'time.daysAgo': 'منذ {n} يوم',
    'time.weeksAgo': 'منذ {n} أسبوع',
    'time.monthsAgo': 'منذ {n} شهر',
    'time.yearsAgo': 'منذ {n} سنة',
  },
  en: {
 // Navbar
'nav.home': 'Home',
'nav.marketplace': 'Marketplace',
'nav.sell': 'Sell Account',
'nav.orders': 'My Orders',
'nav.wallet': 'Wallet',
'nav.profile': 'Profile',
'nav.admin': 'Admin Panel',
'nav.members': 'Members',
'nav.leaderboard': 'Leaderboard',
'nav.help': 'Help Center',
'nav.disputes': 'Disputes',
'nav.myListings': 'My Listings',
'nav.kyc': 'Identity Verification',
'nav.notifications': 'Notifications',
'nav.settings': 'Settings',
'nav.logout': 'Log Out',
'nav.login': 'Log In',
'nav.suggestions': 'Suggestions & Feedback',
'nav.community': 'Community',

// Home
'home.hero.title': 'NXOLand — Your Trusted Platform for Game Account Trading',
'home.hero.subtitle': 'Buy and sell your favorite game accounts easily, securely, and instantly through our smart escrow system.',
'home.hero.browseAccounts': 'Browse Accounts',
'home.hero.learnMore': 'Learn More',

'home.features.security': '🔒 Secure',
'home.features.fast': '⚡ Fast',
'home.features.support': '💬 24/7 Support',

'home.whyChoose': 'Why Choose NXOLand?',

'home.feature1.title': 'Smart Escrow Protection',
'home.feature1.desc': 'Every transaction is protected to ensure both the buyer and seller are fully secured.',

'home.feature2.title': '24/7 Discord Support',
'home.feature2.desc': 'Our dedicated support team is available anytime through Discord for quick assistance.',

'home.feature3.title': 'Fair & Competitive Prices',
'home.feature3.desc': 'Enjoy smooth trades with fair pricing and minimal fees for both sides.',

'home.feature4.title': 'Instant Payouts',
'home.feature4.desc': 'Sellers receive their funds instantly once the buyer confirms account delivery.',

'home.howItWorks': 'How It Works',

'home.step1.title': 'Choose Your Account',
'home.step1.desc': 'Browse thousands of verified accounts across multiple games.',

'home.step2.title': 'Pay Securely',
'home.step2.desc': 'Complete your payment safely using Tap, our trusted payment partner.',

'home.step3.title': 'Receive Instantly',
'home.step3.desc': 'Once payment is confirmed, your game account is delivered instantly.',

'home.cta.title': 'Start Trading with Confidence',
'home.cta.subtitle': 'Join thousands of gamers who trust NXOLand for safe and seamless trading.',
'home.cta.getStarted': 'Get Started',

'home.footer.rights': '© All rights reserved to NXOLand',
'home.footer.terms': 'Terms & Conditions',
'home.footer.privacy': 'Privacy Policy',
'home.footer.support': 'Support',

    
    // Sell
    'sell.title': 'Choose Game',
    'sell.subtitle': 'Select the game you want to sell accounts for',
    'sell.comingSoon': 'More games coming soon...',
    'sell.selectCategory': 'Select Category',
    'sell.categorySubtitle': 'Choose the type of account you want to sell',
    'sell.explore': 'Explore',
    'sell.price': 'Price',
    'sell.description': 'Description',
    'sell.gaming.title': 'Gaming Accounts',
    'sell.gaming.description': 'Sell your gaming accounts',
    'sell.social.title': 'Social Media Accounts',
    'sell.social.description': 'Sell your social media accounts',
    'sell.social.followers': 'Followers',
    'sell.social.likes': 'Likes',
    'sell.social.views': 'Views',
    'sell.social.posts': 'Posts',
    'sell.social.engagement': 'Engagement Rate',
    'sell.social.verification': 'Verification Status',
    'sell.social.verified': 'Verified',
    'sell.social.unverified': 'Unverified',
    'sell.social.tiktok.title': 'Sell TikTok Account',
    'sell.social.tiktok.subtitle': 'Enter your TikTok account details',
    'sell.social.tiktok.description': 'Sell TikTok accounts',
    'sell.social.tiktok.username': 'Username',
    'sell.social.tiktok.descriptionPlaceholder': 'Describe your account, niche, content type, etc...',
    'sell.social.instagram.title': 'Sell Instagram Account',
    'sell.social.instagram.subtitle': 'Enter your Instagram account details',
    'sell.social.instagram.description': 'Sell Instagram accounts',
    'sell.social.instagram.username': 'Username',
    'sell.social.instagram.descriptionPlaceholder': 'Describe your account, niche, content type, etc...',
    'sell.social.accountDescription': 'Account Description',
    'sell.social.descriptionPlaceholder': 'Describe your account, niche, content type, etc...',
    'sell.social.accountWithPrimaryEmail': 'Account with primary email',
    'sell.social.accountLinkedToPhone': 'The account is linked to a phone number',
    'sell.social.confirmOwnership.title': 'Confirmation of ownership and delivery information',
    'sell.social.confirmOwnership.description': 'To ensure a secure environment for buying and selling accounts, you must complete the steps below to add your account.',
    'sell.social.confirmOwnership.instruction': 'Press the Put the word below in your account bio confirmation button to proceed',
    'sell.social.confirmOwnership.theWord': 'The word',
    'sell.social.confirmOwnership.copy': 'Copy',
    'sell.social.confirmOwnership.confirm': 'CONFIRMATION OF OWNERSHIP',
    'sell.social.pledge1': 'I pledge that the product description will be free of any means of communication outside the platform, in any way whatsoever, whether direct or indirect.',
    'sell.social.pledge2': 'I undertake to bear full legal responsibility for all actions taken or issued by the account in question from the date of its creation or purchase until the date of its sale on the User platform, and I guarantee that it is free of any cybercrimes.',
    'sell.social.deliveryInfo.title': 'Delivery Information',
    'sell.social.deliveryInfo.description': 'Enter the account credentials that will be delivered to the buyer',
    'sell.social.deliveryInfo.email': 'Email Address',
    'sell.social.deliveryInfo.password': 'Password',
    'sell.social.deliveryInfo.instructions': 'Delivery Instructions',
    'sell.social.deliveryInfo.instructionsPlaceholder': 'Any additional information for the buyer about delivery...',
    
    // Listing
    'listing.success': 'Listing created successfully!',
    'listing.successDescription': 'Your listing will be reviewed and published soon.',
    'listing.creating': 'Creating...',
    'listing.create': 'Create Listing',
    
    // Common
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.back': 'Back',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.update': 'Update',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.page': 'Page',
    'common.of': 'of',
    'common.showing': 'Showing',
    'common.results': 'results',
    'common.noResults': 'No results found',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    
    // Auth
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.rememberMe': 'Remember Me',
    'auth.haveAccount': 'Already have an account?',
    'auth.noAccount': "Don't have an account?",
    'auth.loginButton': 'Login',
    'auth.signupButton': 'Create Account',
    'auth.loginSuccess': 'Login successful',
    'auth.signupSuccess': 'Account created successfully',
    'auth.loginError': 'Login failed',
    'auth.signupError': 'Account creation failed',
    'auth.invalidEmail': 'Please enter a valid email',
    'auth.passwordTooShort': 'Password must be at least',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.nameTooShort': 'Name must be at least',
    'auth.agreeToTerms': 'By creating an account, you agree to',
    'auth.and': 'and',
    'auth.backToHome': 'Back to Home',
    'auth.processing': 'Processing...',
    'auth.securityVerification': 'Please complete security verification',
    
    // Marketplace
    'marketplace.title': 'Marketplace',
    'marketplace.subtitle': 'Browse all available accounts',
    'marketplace.searchPlaceholder': 'Search accounts...',
    'marketplace.filterBy': 'Filter by',
    'marketplace.sortBy': 'Sort by',
    'marketplace.allGames': 'All Games',
    'marketplace.priceRange': 'Price Range',
    'marketplace.level': 'Level',
    'marketplace.server': 'Server',
    'marketplace.latest': 'Latest',
    'marketplace.priceHigh': 'Price (High to Low)',
    'marketplace.priceLow': 'Price (Low to High)',
    'marketplace.levelHigh': 'Level (High to Low)',
    'marketplace.noListings': 'No listings found',
    'marketplace.noListingsDesc': 'No accounts match your search',
    'marketplace.tryDifferent': 'Try adjusting your search or filters',
    'marketplace.verified': 'Verified',
    'marketplace.featured': 'Featured',
    'marketplace.viewDetails': 'View Details',
    
    // Product Details
    'product.details': 'Account Details',
    'product.price': 'Price',
    'product.level': 'Level',
    'product.server': 'Server',
    'product.seller': 'Seller',
    'product.description': 'Description',
    'product.specifications': 'Specifications',
    'product.images': 'Images',
    'product.buyNow': 'Buy Now',
    'product.addToCart': 'Add to Cart',
    'product.sellerInfo': 'Seller Information',
    'product.sellerRating': 'Seller Rating',
    'product.totalSales': 'Total Sales',
    'product.memberSince': 'Member Since',
    'product.responseTime': 'Response Time',
    'product.deliveryTime': 'Delivery Time',
    'product.viewProfile': 'View Profile',
    'product.reportListing': 'Report Listing',
    'product.share': 'Share',
    'product.clickToEnlarge': 'Click to enlarge',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.orderSummary': 'Order Summary',
    'checkout.productDetails': 'Product Details',
    'checkout.subtotal': 'Subtotal',
    'checkout.serviceFee': 'Service Fee',
    'checkout.total': 'Total',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.agreeToTerms': 'I agree to the Terms & Conditions',
    'checkout.confirmPurchase': 'Confirm Purchase',
    'checkout.processing': 'Processing...',
    'checkout.securePayment': 'Secure payment via',
    'checkout.buyerProtection': '12-hour buyer protection',
    'checkout.deliveryInfo': 'Delivery Information',
    'checkout.instantDelivery': 'Instant delivery after payment',
    'checkout.mustAgreeTerms': 'You must agree to the Terms & Conditions',
    
    // Orders
    'orders.title': 'My Orders',
    'orders.subtitle': 'View and manage all your orders',
    'orders.searchPlaceholder': 'Search by order ID, product, or seller...',
    'orders.filterByRole': 'Show orders:',
    'orders.all': 'All',
    'orders.asBuyer': 'As Buyer',
    'orders.asSeller': 'As Seller',
    'orders.status': 'Status',
    'orders.pending': 'Pending Payment',
    'orders.paid': 'Paid',
    'orders.escrowHold': 'In Escrow',
    'orders.completed': 'Completed',
    'orders.cancelled': 'Cancelled',
    'orders.disputed': 'Disputed',
    'orders.noOrders': 'No orders yet',
    'orders.noOrdersDesc': 'You haven\'t made any purchases yet',
    'orders.noOrdersFilter': 'No orders match the selected filter',
    'orders.browseMarket': 'Browse Marketplace',
    'orders.viewDetails': 'View Details',
    'orders.contactSeller': 'Contact Seller',
    'orders.openDispute': 'Open Dispute',
    'orders.viewDispute': 'View Dispute',
    'orders.confirmReceipt': 'Confirm Receipt',
    'orders.orderNumber': 'Order Number',
    'orders.date': 'Date',
    'orders.buyer': 'Buyer',
    'orders.seller': 'Seller',
    'orders.amount': 'Amount',
    'orders.stats.total': 'Total',
    'orders.stats.asBuyer': 'As Buyer',
    'orders.stats.asSeller': 'As Seller',
    'orders.stats.inEscrow': 'In Escrow',
    'orders.stats.completed': 'Completed',
    'orders.stats.cancelled': 'Cancelled',
    
    // Order Details
    'order.title': 'Order Details',
    'order.status': 'Order Status',
    'order.timeline': 'Timeline',
    'order.productInfo': 'Product Information',
    'order.accountDetails': 'Account Details',
    'order.paymentInfo': 'Payment Information',
    'order.actions': 'Actions',
    'order.confirmDelivery': 'Confirm Receipt',
    'order.openDispute': 'Open Dispute',
    'order.cancelOrder': 'Cancel Order',
    'order.contactSupport': 'Contact Support',
    'order.downloadInvoice': 'Download Invoice',
    'order.escrowPeriod': 'Escrow Period',
    'order.escrowEndsIn': 'Escrow ends in',
    'order.hours': 'hours',
    'order.minutes': 'minutes',
    'order.delivered': 'Delivered',
    'order.deliveredAt': 'Delivered at',
    
    // Wallet
    'wallet.title': 'Wallet',
    'wallet.balance': 'Available Balance',
    'wallet.pending': 'Pending',
    'wallet.total': 'Total',
    'wallet.withdraw': 'Withdraw',
    'wallet.deposit': 'Deposit',
    'wallet.transactions': 'Transactions',
    'wallet.withdrawalHistory': 'Withdrawal History',
    'wallet.amount': 'Amount',
    'wallet.enterAmount': 'Enter amount',
    'wallet.minimumWithdrawal': 'Minimum withdrawal',
    'wallet.bankAccount': 'Bank Account',
    'wallet.accountNumber': 'Account Number',
    'wallet.accountName': 'Account Holder Name',
    'wallet.bankName': 'Bank Name',
    'wallet.iban': 'IBAN',
    'wallet.requestWithdrawal': 'Request Withdrawal',
    'wallet.withdrawalRequested': 'Withdrawal requested successfully',
    'wallet.withdrawalPending': 'Processing',
    'wallet.withdrawalCompleted': 'Completed',
    'wallet.withdrawalFailed': 'Failed',
    'wallet.transactionType': 'Transaction Type',
    'wallet.sale': 'Sale',
    'wallet.purchase': 'Purchase',
    'wallet.withdrawal': 'Withdrawal',
    'wallet.refund': 'Refund',
    'wallet.fee': 'Fee',
    'wallet.noTransactions': 'No transactions yet',
    'wallet.processingTime': 'Processing time: 1-4 business days',
    
    // Profile
    'profile.title': 'Profile',
    'profile.publicProfile': 'Public Profile',
    'profile.memberSince': 'Member Since',
    'profile.lastActive': 'Last Active',
    'profile.verified': 'Verified',
    'profile.notVerified': 'Not Verified',
    'profile.rating': 'Rating',
    'profile.totalSales': 'Total Sales',
    'profile.completedOrders': 'Completed Orders',
    'profile.activeListings': 'Active Listings',
    'profile.responseRate': 'Response Rate',
    'profile.deliveryTime': 'Delivery Time',
    'profile.editProfile': 'Edit Profile',
    'profile.viewReviews': 'View Reviews',
    'profile.accountSettings': 'Account Settings',
    'profile.security': 'Security',
    'profile.verifyAccount': 'Verify Account',
    'profile.about': 'About',
    'profile.noReviews': 'No reviews yet',
    'profile.reviewsCount': 'reviews',
    
    // Edit Profile
    'editProfile.title': 'Edit Profile',
    'editProfile.personalInfo': 'Personal Information',
    'editProfile.name': 'Name',
    'editProfile.email': 'Email',
    'editProfile.phone': 'Phone',
    'editProfile.bio': 'Bio',
    'editProfile.avatar': 'Avatar',
    'editProfile.changeAvatar': 'Change Avatar',
    'editProfile.saveChanges': 'Save Changes',
    'editProfile.saving': 'Saving...',
    'editProfile.updateSuccess': 'Profile updated successfully',
    'editProfile.updateError': 'Update failed',
    
    // Security
    'security.title': 'Security',
    'security.changePassword': 'Change Password',
    'security.currentPassword': 'Current Password',
    'security.newPassword': 'New Password',
    'security.confirmNewPassword': 'Confirm New Password',
    'security.updatePassword': 'Update Password',
    'security.passwordUpdated': 'Password updated successfully',
    'security.twoFactor': 'Two-Factor Authentication',
    'security.enable2FA': 'Enable 2FA',
    'security.disable2FA': 'Disable 2FA',
    'security.loginHistory': 'Login History',
    'security.activeSessions': 'Active Sessions',
    'security.logoutAll': 'Logout All Devices',
    
    // KYC
    'kyc.title': 'KYC Verification',
    'kyc.subtitle': 'Complete identity verification to increase withdrawal limit',
    'kyc.status': 'Verification Status',
    'kyc.notStarted': 'Not Started',
    'kyc.pending': 'Under Review',
    'kyc.verified': 'Verified',
    'kyc.rejected': 'Rejected',
    'kyc.startVerification': 'Start Verification',
    'kyc.resubmit': 'Resubmit',
    'kyc.benefits': 'Verification Benefits',
    'kyc.benefit1': 'Increase withdrawal limit to $10,000',
    'kyc.benefit2': 'Verified badge on your profile',
    'kyc.benefit3': 'Increased trust from buyers',
    'kyc.benefit4': 'Priority support',
    'kyc.requiredDocs': 'Required Documents',
    'kyc.nationalId': 'National ID',
    'kyc.proofOfAddress': 'Proof of Address',
    'kyc.selfie': 'Selfie',
    
    // My Listings
    'listings.title': 'My Listings',
    'listings.subtitle': 'Manage all your listings',
    'listings.createNew': 'Create New Listing',
    'listings.active': 'Active',
    'listings.pending': 'Pending Review',
    'listings.sold': 'Sold',
    'listings.rejected': 'Rejected',
    'listings.draft': 'Draft',
    'listings.noListings': 'No listings yet',
    'listings.createFirst': 'Create your first listing',
    'listings.edit': 'Edit',
    'listings.delete': 'Delete',
    'listings.view': 'View',
    'listings.promote': 'Promote',
    'listings.views': 'views',
    'listings.inquiries': 'inquiries',
    'listings.deleteConfirm': 'Are you sure you want to delete this listing?',
    
    // Disputes
    'disputes.title': 'Disputes',
    'disputes.subtitle': 'Manage disputes and complaints',
    'disputes.openDispute': 'Open Dispute',
    'disputes.myDisputes': 'My Disputes',
    'disputes.status': 'Status',
    'disputes.open': 'Open',
    'disputes.inReview': 'Under Review',
    'disputes.resolved': 'Resolved',
    'disputes.closed': 'Closed',
    'disputes.orderNumber': 'Order Number',
    'disputes.reason': 'Reason',
    'disputes.description': 'Description',
    'disputes.evidence': 'Evidence',
    'disputes.uploadEvidence': 'Upload Evidence',
    'disputes.submitDispute': 'Submit Dispute',
    'disputes.noDisputes': 'No disputes',
    'disputes.viewDetails': 'View Details',
    'disputes.adminResponse': 'Admin Response',
    'disputes.resolution': 'Resolution',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark All as Read',
    'notifications.deleteAll': 'Delete All',
    'notifications.noNotifications': 'No notifications',
    'notifications.newOrder': 'New Order',
    'notifications.orderUpdate': 'Order Update',
    'notifications.disputeOpened': 'New Dispute',
    'notifications.disputeResolved': 'Dispute Resolved',
    'notifications.paymentReceived': 'Payment Received',
    'notifications.withdrawalCompleted': 'Withdrawal Completed',
    'notifications.newReview': 'New Review',
    'notifications.kycUpdate': 'KYC Update',
    
    // Members & Leaderboard
    'members.title': 'Members',
    'members.subtitle': 'Browse platform members',
    'members.searchMembers': 'Search members...',
    'members.topSellers': 'Top Sellers',
    'members.topBuyers': 'Top Buyers',
    'members.newMembers': 'New Members',
    'leaderboard.title': 'Leaderboard',
    'leaderboard.subtitle': 'Top sellers and buyers',
    'leaderboard.rank': 'Rank',
    'leaderboard.member': 'Member',
    'leaderboard.sales': 'Sales',
    'leaderboard.rating': 'Rating',
    'leaderboard.topSeller': '#1',
    
    // Reviews
    'reviews.title': 'Reviews',
    'reviews.writeReview': 'Write Review',
    'reviews.yourRating': 'Your Rating',
    'reviews.yourReview': 'Your Review',
    'reviews.submitReview': 'Submit Review',
    'reviews.helpful': 'Helpful',
    'reviews.notHelpful': 'Not Helpful',
    'reviews.report': 'Report',
    'reviews.noReviews': 'No reviews yet',
    'reviews.verifiedPurchase': 'Verified Purchase',
    
    // Suggestions
    'suggestions.title': 'Suggestions & Feedback Center',
    'suggestions.subtitle': 'Share your ideas and rate your experience',
    'suggestions.platformRating': 'Rate Your Experience',
    'suggestions.yourRating': 'Your Platform Rating',
    'suggestions.yourFeedback': 'Tell us about your experience',
    'suggestions.submitRating': 'Submit Rating',
    'suggestions.newSuggestion': 'Platform Improvement Suggestion',
    'suggestions.suggestionTitle': 'Suggestion Title',
    'suggestions.suggestionDesc': 'Describe your suggestion in detail...',
    'suggestions.submitSuggestion': 'Submit Suggestion',
    'suggestions.upvote': 'Upvote',
    'suggestions.downvote': 'Downvote',
    'suggestions.votes': 'votes',
    'suggestions.status.pending': 'Under Review',
    'suggestions.status.approved': 'Approved',
    'suggestions.status.implemented': 'Implemented',
    
    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.listings': 'Listings',
    'admin.orders': 'Orders',
    'admin.disputes': 'Disputes',
    'admin.notifications': 'Notifications',
    'admin.settings': 'Settings',
    'admin.legalContent': 'Legal Content',
    'admin.stats': 'Statistics',
    'admin.activity': 'Recent Activity',
    'admin.totalUsers': 'Total Users',
    'admin.activeListings': 'Active Listings',
    'admin.pendingOrders': 'Pending Orders',
    'admin.openDisputes': 'Open Disputes',
    'admin.revenue': 'Revenue',
    'admin.actions': 'Actions',
    'admin.ban': 'Ban',
    'admin.unban': 'Unban',
    'admin.verify': 'Verify',
    'admin.reject': 'Reject',
    'admin.approve': 'Approve',
    'admin.viewDetails': 'View Details',
    'admin.sendNotification': 'Send Notification',
    'admin.broadcastMessage': 'Broadcast Message',
    
    // Help & Support
    'help.title': 'Help',
    'help.faq': 'Frequently Asked Questions',
    'help.contactSupport': 'Contact Support',
    'help.searchHelp': 'Search for help...',
    'help.popularTopics': 'Popular Topics',
    'help.gettingStarted': 'Getting Started',
    'help.buyingGuide': 'Buying Guide',
    'help.sellingGuide': 'Selling Guide',
    'help.accountSecurity': 'Account Security',
    'help.paymentsAndFees': 'Payments & Fees',
    
    // About
    'about.title': 'About Us',
    'about.ourMission': 'Our Mission',
    'about.ourVision': 'Our Vision',
    'about.ourValues': 'Our Values',
    'about.team': 'Team',
    'about.contact': 'Contact Us',
    
    // Error Messages
    'error.404': 'Page Not Found',
    'error.404.desc': 'Sorry, the page you are looking for does not exist',
    'error.500': 'Server Error',
    'error.500.desc': 'An unexpected error occurred',
    'error.networkError': 'Network Error',
    'error.tryAgain': 'Try Again',
    'error.goHome': 'Go Home',
    'error.forbidden': 'Forbidden',
    'error.unauthorized': 'Please login',
    'error.sessionExpired': 'Session Expired',
    
    // Status Messages
    'status.loading': 'Loading...',
    'status.saving': 'Saving...',
    'status.uploading': 'Uploading...',
    'status.processing': 'Processing...',
    'status.success': 'Success',
    'status.failed': 'Failed',
    'status.pending': 'Pending',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    
    // Time & Date
    'time.justNow': 'Just now',
    'time.minutesAgo': '{n} minutes ago',
    'time.hoursAgo': '{n} hours ago',
    'time.daysAgo': '{n} days ago',
    'time.weeksAgo': '{n} weeks ago',
    'time.monthsAgo': '{n} months ago',
    'time.yearsAgo': '{n} years ago',
  }
};
