/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1Hn4NBB5sATdK2CZK8S6bB

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsk89Wej0TRoq8 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: k89WEJ0tROQ8/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsk89Wej0TRoq8
});
