/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1Hn4NBB5sATdK2CZK8S6bB

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 1Hn4NBB5sATdK2CZK8S6bB/projectModule

import projectcss from "./plasmic.module.css"; // plasmic-import: 1Hn4NBB5sATdK2CZK8S6bB/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
